### ISSUE TITLE
Several typos in README

### ISSUE THREAD

**Issue by gamtiq** [nskazki/bellman#1]
There are the following typos in README:

> Аккуратный _консольныый_ логгер.
> минимальной ширины _отводмой_ под столбец
> в качестве _агрумента_ события используется _объет_, содержащий
> Корень _дирректории_ проекта
> Параметр может быть так же _задани_ при _момощи_ переменных окружения

**Comment by nskazki** [comment]
Thanks for the report. Readme has been recently re-written in English. Closing the issue.
